[package]
name = "brb"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.17"
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
tui-big-text = "0.6.0"
twitch-irc = "5.0.1"
